---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16


      - name: Build Windows
        run: env GOOS=windows GOARCH=amd64 go build -o solo-providers-git-github.win-amd64
      - name: Build Mac
        run: env GOOS=darwin GOARCH=amd64 go build -o solo-providers-git-github.darwin-amd64
      - name: Build Linux
        run: env GOOS=linux GOARCH=amd64 go build -o solo-providers-git-github.linux-amd64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            solo-providers-git-github.*
            LICENSE
            README.md
